import Head from 'next/head'
import Image from 'next/image'
import { Box, Grid, Paper, Stack, Typography, Container } from "@mui/material";
import Colors from '@/common/Colorscomponents';
import AIRAMonoLinesLeft from '@/components/AIRAMonoLinesLeft/AIRAMonoLinesLeftcomponents';
import RoundedButton from '@/components/RoundedButton/RoundedButtoncomponents';
import macBookImage from '../../public/images/home/macbook.svg'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next';
import styles from '../styles/Home.module.css'
import RefereceStack from '@/components/ReferenceStack/RefereceStackcomponents';
import PowerOfIntelligence from '@/components/PowerOfIntelligence/PowerOfIntelligencecomponents';
import Offering from '@/components/Offering/Offeringcomponents';
import ConnectToSystem from '@/components/ConnectToSystem/ConnectToSystemcomponents';
import DiscoverStack from '../components/DiscoverStack/DiscoverStack';

const EBONYHEIGHT = "600";

function Home() {
  const { t } = useTranslation('common')
  return (
    <>
      <Head>
        <title>AIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/monogram.svg" />
      </Head>

      <Box sx={{ pt: { xs: 8.5, md: 0 } }}>
        <Paper sx={{ position: "relative" }} elevation={0}>
          <Grid
            container
            justifyContent="center"
            alignItems="center"
            flexDirection={{ xs: "column-reverse", md: "row" }}
          >
            <Grid item xs={12} md={6}>
              <Container>
                <Box
                  sx={{
                    width: '100%',
                    display: 'flex',
                    justifyContent: 'flex-end',
                    alignItems: 'flex-end',
                    flexDirection: 'column'
                  }}
                >
                  <Box sx={{ width: { xs: '100%', md: '60%' }, pt: { xs: 5, md: 0 } }}>
                    <Typography variant="h4" sx={{ fontWeight: 800 }}>
                      Revolutionize Your Productivity With{" "}
                      <span style={{ color: Colors.airaSecondary }}>
                        AI Automation
                      </span>
                    </Typography>

                    <Typography variant="body1" sx={{ mt: 3 }}>
                      <span style={{ fontWeight: 700 }}>
                        Artificially Intelligent Robotic Automation,
                      </span>{" "}
                      Say goodbye to manual tasks and hello to a more efficient and
                      profitable enterprise.
                    </Typography>
                    <RoundedButton label="Request Demo" sx={{ mt: 3 }} />
                  </Box>
                </Box>
              </Container>
            </Grid>
            <Grid item xs={12} md={6}>
              <Box
                sx={{
                  width: "100%",
                  backgroundImage: "url(/images/home/ebony.png)",
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "right top",
                  backgroundSize: 'cover',
                  height: '55vw',
                  display: 'flex',
                  justifyContent: 'start',
                  alignItems: 'center',
                }}
              >
                <Box sx={{ py: 5 }}>
                  <Image
                    src={macBookImage}
                    width={0}
                    height={0}
                    alt='AIRA'
                    sizes="100vw"
                    // style={{ width: '100%', height: 'auto' }}
                    className={styles.macbookImage}
                  />
                </Box>
              </Box>
            </Grid>
          </Grid>

          <Container maxWidth="lg">
            <Grid
              sx={{ pt: 4 }}
              container
              spacing={5}
              justifyContent="left"
              alignItems="center"
            >
              <Grid item xs={12} md={6}>
                <div style={{ position: "relative" }}>
                  <div
                    style={{
                      height: "140px",
                      width: "40px",
                      position: "absolute",
                      transform: "rotate(35deg)",
                      borderRadius: "50px",
                      backgroundColor: Colors.airaPrimary,
                      top: 150,
                      marginLeft: "-30px",
                    }}
                  ></div>
                  <div
                    style={{
                      height: "140px",
                      width: "40px",
                      top: 200,
                      transform: "rotate(35deg)",
                      position: "absolute",
                      borderRadius: "50px",
                      backgroundColor: Colors.airaSecondary,
                    }}
                  ></div>
                  <div
                    style={{
                      height: "140px",
                      width: "40px",
                      transform: "rotate(35deg)",
                      top: 250,
                      position: "absolute",
                      borderRadius: "50px",
                      marginLeft: "35px",
                      border: `1px solid ${Colors.airaPrimary}`,
                    }}
                  ></div>
                  <Image
                    src="/images/home/learnmore.png"
                    alt="bankingheader"
                    width={0}
                    height={0}
                    sizes="100vw"
                    style={{ width: '100%', height: 'auto', zIndex: 2 }}
                  />
                </div>
              </Grid>
              <Grid item xs={12} md={6}>
                <Stack direction="column" sx={{ py: 2 }}>
                  <Typography variant="h5" sx={{ fontsize: "20 px", fontWeight: 700 }}>
                    <span style={{ color: Colors.airaSecondary }}>AIRA:</span>{" "}
                    Artificially Intelligent Robotic Automation
                  </Typography>
                  <Typography variant="body1" sx={{ mt: 2, fontWeight: 600 }}>
                    Automated Bots for your Digital Transformation
                  </Typography>
                  <Typography variant="body1" sx={{ mt: 2, lineHeight: 2 }}>
                    Introducing AIRA, an AI and ML-powered digital agent that automates
                    your everyday tasks and business processes through robotic
                    automation. It integrates with digital technologies and legacy
                    systems, freeing your workforce from low-output tasks. With AIRA,
                    you can create personalised low-code/no-code automated workflows.
                  </Typography>
                  <div>
                    <RoundedButton label="Learn more" sx={{ mt: 3 }} />
                  </div>
                </Stack>
              </Grid>
            </Grid>
          </Container>

          <Container maxWidth="lg">
            <DiscoverStack />
            <Box sx={{ display: "flex", justifyContent: "center", alignSelf: "center", pt: 3 }}>
              <RoundedButton label="Try AIRA" sx={{ px: 5 }} />
            </Box>
            <Box sx={{ py: 6 }}>
              <RefereceStack />
            </Box>
            <Box>
              <PowerOfIntelligence />
            </Box>
            <Box>
              <Offering />
            </Box>
            <Box>
              <ConnectToSystem />
            </Box>
          </Container>

          {/* <div
            style={{
              position: "absolute",
              right: 0,
              top: 0,
            }}
          >
            <Image
              src="/images/home/ebony.png"
              alt="contact us"
              width="500"
              sizes="100vw"
              height={EBONYHEIGHT}
              style={{
                zIndex: 1,
                // marginRight: "10px",
                alignSelf: "flex-end",
              }}
            />
          </div> */}
          <Box
            sx={{
              position: 'absolute',
              top: 100,
              display: { xs: 'none', md: 'block' }
            }}
          // style={{
          //   position: "absolute",
          //   top: 100,
          // }}
          >
            <AIRAMonoLinesLeft />
          </Box>
        </Paper>
      </Box>
    </>
  )
}

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'footer'])),
  },
})

export default Home;
